name: tree-view-app

services:
  mongo:
    image: mongo:7.0.12
    container_name: db_c
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - tree-view-app

  server:
    build:
      context: ./server
      target: development
    container_name: server_c
    restart: unless-stopped
    env_file: ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - tree-view-app
    depends_on:
      - mongo

  client:
    build:
      context: ./client
      target: development
      args:
        REACT_APP_API_URL: https://api.treeview.localhost
    container_name: client_c
    restart: unless-stopped
    env_file: ./client/.env
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - tree-view-app
    depends_on:
      - server

  caddy:
    image: caddy:2-alpine
    container_name: caddy_c
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy/Caddyfile.dev:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - tree-view-app
    depends_on:
      - server
      - client

volumes:
  mongo_data:
  caddy_data:
  caddy_config:

networks:
  tree-view-app:
    driver: bridge
