name: tree-view-app

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server_c
    env_file: ./server/.env
    ports:
      - 5000:5000
    restart: unless-stopped
    
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client_c
    ports:
      - 3000:3000
    restart: unless-stopped
